// AUTO-GENERATED by scripts/update-hltv-card-stats.py.
// Initial empty snapshot so the application stays buildable before the first refresh.

import type { HltvPlayerSnapshot } from './cardStats'

export const HLTV_CARD_SNAPSHOT_META = {
  source: 'HLTV',
  startDate: '2025-09-26',
  endDate: '2026-09-26',
  generatedAt: null,
  requestedPlayers: 1634,
  matchedProfiles: 0,
  withStats: 0,
} as const

export const HLTV_CARD_SNAPSHOTS: Readonly<Record<string, HltvPlayerSnapshot>> = {}
