import { VRS_PLAYERS } from './vrs'
import { metadataForAlias } from './playerMetadata'

export type RealPlayerRole = 'IGL' | 'Entry' | 'Rifler' | 'AWP' | 'Support'

export interface RealPlayerSeed {
  alias: string
  realName: string | null
  country: string | null
  team: string
  age: number | null
  role: RealPlayerRole | null
  rating: number | null
  vrsRank?: number | null
  source?: 'curated-profile' | 'valve-vrs'
  profileUrl?: string | null
}

// Identity, nationality, current team and age were verified against current HLTV
// profiles/lineups on 2026-09-26. `rating` is used only as a balancing seed.
// The detailed in-game attributes are generated by our own game model.
const CURATED_REAL_PLAYERS: readonly RealPlayerSeed[] = [
  // Spirit
  { alias: 'sh1ro', realName: 'Dmitry Sokolov', country: 'Russia', team: 'Spirit', age: 25, role: 'AWP', rating: 1.15 },
  { alias: 'magixx', realName: 'Boris Vorobiev', country: 'Russia', team: 'Spirit', age: 23, role: 'IGL', rating: 0.94 },
  { alias: 'tN1R', realName: 'Andrey Tatarinovich', country: 'Belarus', team: 'Spirit', age: 25, role: 'Rifler', rating: 1.05 },
  { alias: 'zont1x', realName: 'Myroslav Plakhotia', country: 'Ukraine', team: 'Spirit', age: 21, role: 'Support', rating: 1.01 },
  { alias: 'donk', realName: 'Danil Kryshkovets', country: 'Russia', team: 'Spirit', age: 19, role: 'Entry', rating: 1.41 },

  // Vitality
  { alias: 'apEX', realName: 'Dan Madesclaire', country: 'France', team: 'Vitality', age: 33, role: 'IGL', rating: 0.94 },
  { alias: 'ropz', realName: 'Robin Kool', country: 'Estonia', team: 'Vitality', age: 26, role: 'Rifler', rating: 1.06 },
  { alias: 'ZywOo', realName: 'Mathieu Herbaut', country: 'France', team: 'Vitality', age: 25, role: 'AWP', rating: 1.32 },
  { alias: 'flameZ', realName: 'Shahar Shushan', country: 'Israel', team: 'Vitality', age: 23, role: 'Entry', rating: 1.08 },
  { alias: 'mezii', realName: 'William Merriman', country: 'United Kingdom', team: 'Vitality', age: 27, role: 'Support', rating: 1.02 },

  // MOUZ
  { alias: 'torzsi', realName: 'Ádám Torzsás', country: 'Hungary', team: 'MOUZ', age: 24, role: 'AWP', rating: 1.11 },
  { alias: 'Spinx', realName: 'Lotan Giladi', country: 'Israel', team: 'MOUZ', age: 26, role: 'Rifler', rating: 1.12 },
  { alias: 'xertioN', realName: 'Dorian Berman', country: 'Israel', team: 'MOUZ', age: 22, role: 'IGL', rating: 1.09 },
  { alias: 'PR', realName: 'Oldřich Nový', country: 'Czech Republic', team: 'MOUZ', age: 19, role: 'Support', rating: 0.98 },
  { alias: 'xelex', realName: 'Adrian Vincze', country: 'Hungary', team: 'MOUZ', age: 18, role: 'Entry', rating: 1.05 },

  // FURIA
  { alias: 'FalleN', realName: 'Gabriel Toledo', country: 'Brazil', team: 'FURIA', age: 35, role: 'IGL', rating: 0.90 },
  { alias: 'yuurih', realName: 'Yuri Santos', country: 'Brazil', team: 'FURIA', age: 26, role: 'Rifler', rating: 0.94 },
  { alias: 'YEKINDAR', realName: 'Mareks Gaļinskis', country: 'Latvia', team: 'FURIA', age: 26, role: 'Entry', rating: 1.06 },
  { alias: 'KSCERATO', realName: 'Kaike Cerato', country: 'Brazil', team: 'FURIA', age: 27, role: 'Rifler', rating: 1.21 },
  { alias: 'molodoy', realName: 'Danil Golubenko', country: 'Kazakhstan', team: 'FURIA', age: 21, role: 'AWP', rating: 1.10 },

  // Falcons
  { alias: 'karrigan', realName: 'Finn Andersen', country: 'Denmark', team: 'Falcons', age: 36, role: 'IGL', rating: 0.81 },
  { alias: 'NiKo', realName: 'Nikola Kovač', country: 'Bosnia and Herzegovina', team: 'Falcons', age: 29, role: 'Rifler', rating: 1.04 },
  { alias: 'TeSeS', realName: 'René Madsen', country: 'Denmark', team: 'Falcons', age: 25, role: 'Support', rating: 1.02 },
  { alias: 'm0NESY', realName: 'Ilya Osipov', country: 'Russia', team: 'Falcons', age: 21, role: 'AWP', rating: 1.28 },
  { alias: 'kyousuke', realName: 'Maksim Lukin', country: 'Russia', team: 'Falcons', age: 18, role: 'Entry', rating: 1.15 },

  // Natus Vincere
  { alias: 'Aleksib', realName: 'Aleksi Virolainen', country: 'Finland', team: 'Natus Vincere', age: 29, role: 'IGL', rating: 0.93 },
  { alias: 'iM', realName: 'Mihai Ivan', country: 'Romania', team: 'Natus Vincere', age: 27, role: 'Entry', rating: 1.10 },
  { alias: 'b1t', realName: 'Valeriy Vakhovskiy', country: 'Ukraine', team: 'Natus Vincere', age: 23, role: 'Rifler', rating: 1.12 },
  { alias: 'w0nderful', realName: 'Ihor Zhdanov', country: 'Ukraine', team: 'Natus Vincere', age: 21, role: 'AWP', rating: 1.11 },
  { alias: 'makazze', realName: 'Drin Shaqiri', country: 'Kosovo', team: 'Natus Vincere', age: 19, role: 'Rifler', rating: 1.03 },
] as const


const curatedAliases = new Set(CURATED_REAL_PLAYERS.map((player) => player.alias.toLocaleLowerCase('en-US')))

const VRS_ONLY_PLAYERS: readonly RealPlayerSeed[] = VRS_PLAYERS
  .filter((player) => !curatedAliases.has(player.alias.toLocaleLowerCase('en-US')))
  .map((player) => {
    const metadata = metadataForAlias(player.alias)
    return {
      alias: player.alias,
      realName: metadata?.realName ?? null,
      country: metadata?.country ?? null,
      team: player.team,
      age: metadata?.age ?? null,
      role: metadata?.role ?? null,
      rating: null,
      vrsRank: player.teamRank,
      source: 'valve-vrs' as const,
      profileUrl: metadata?.profileUrl ?? null,
    }
  })

export const REAL_PLAYERS: readonly RealPlayerSeed[] = [
  ...CURATED_REAL_PLAYERS,
  ...VRS_ONLY_PLAYERS,
]

export const REAL_PLAYER_STATS = {
  curatedProfiles: CURATED_REAL_PLAYERS.length,
  vrsOnlyPlayers: VRS_ONLY_PLAYERS.length,
  totalPlayers: REAL_PLAYERS.length,
} as const
