// Generated identity enrichment for VRS players.
// VRS remains authoritative for the team snapshot; this file only fills profile metadata.
// Null/unknown values are preserved rather than fabricated.

import type { RealPlayerRole } from './players'

export interface PlayerMetadata {
  realName: string | null
  country: string | null
  age: number | null
  role: RealPlayerRole | null
  profileUrl: string | null
  source: string
}

export const PLAYER_METADATA: Readonly<Record<string, PlayerMetadata>> = {
  "1eer": {"realName":null,"country":"Belarus","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21266/1eer","source":"PHSix/guess_cspro · Jan 2026"},
  "910": {"realName":"Usukhbayar Banzragch","country":"Mongolia","age":24,"role":"AWP","profileUrl":"https://www.hltv.org/player/21809/910","source":"Sopenfi/skindle · Spring 2026"},
  "acor": {"realName":null,"country":"Denmark","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/10330/acor","source":"PHSix/guess_cspro · Jan 2026"},
  "adamb": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20878/adamb","source":"PHSix/guess_cspro · Jan 2026"},
  "adams": {"realName":null,"country":"Romania","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19698/adams","source":"PHSix/guess_cspro · Jan 2026"},
  "adren": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7433/adren","source":"PHSix/guess_cspro · Jan 2026"},
  "aleksib": {"realName":"Aleksi Virolainen","country":"Finland","age":29,"role":"IGL","profileUrl":"https://www.hltv.org/player/9816/aleksib","source":"Sopenfi/skindle · Spring 2026"},
  "alex": {"realName":null,"country":"United Kingdom","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8184/alex","source":"PHSix/guess_cspro · Jan 2026"},
  "alex666": {"realName":"Alexey Yarmoshchuk","country":"Ukraine","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20112/alex666","source":"Sopenfi/skindle · Spring 2026"},
  "alistair": {"realName":"Alistair Johnston","country":"Australia","age":28,"role":"AWP","profileUrl":"https://www.hltv.org/player/11139/alistair","source":"Sopenfi/skindle · Spring 2026"},
  "alkaren": {"realName":"Alimzhan Bitimbay","country":"Kazakhstan","age":19,"role":"AWP","profileUrl":"https://www.hltv.org/player/23600/alkaren","source":"Sopenfi/skindle · Spring 2026"},
  "allu": {"realName":"Aleksi Jalli","country":"Finland","age":34,"role":"IGL","profileUrl":"https://www.hltv.org/player/695/allu","source":"Sopenfi/skindle · Spring 2026"},
  "amanek": {"realName":null,"country":"France","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9616/amanek","source":"PHSix/guess_cspro · Jan 2026"},
  "annihilation": {"realName":null,"country":"Mongolia","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/18689/annihilation","source":"PHSix/guess_cspro · Jan 2026"},
  "apex": {"realName":"Dan Madesclaire","country":"France","age":33,"role":"IGL","profileUrl":"https://www.hltv.org/player/7322/apex","source":"Sopenfi/skindle · Spring 2026"},
  "ariucle": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21396/ariucle","source":"PHSix/guess_cspro · Jan 2026"},
  "art": {"realName":"Andrei Piovezan","country":"Brazil","age":30,"role":"IGL","profileUrl":"https://www.hltv.org/player/12521/art","source":"Sopenfi/skindle · Spring 2026"},
  "artfr0st": {"realName":"Artem Kharitonov","country":"Russia","age":24,"role":"AWP","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "arvid": {"realName":"Tony Niemelä","country":"Finland","age":29,"role":"IGL","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "autimatic": {"realName":"Timothy Ta","country":"USA","age":30,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8735/autimatic","source":"Sopenfi/skindle · Spring 2026"},
  "aw": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22076/aw","source":"PHSix/guess_cspro · Jan 2026"},
  "ax1le": {"realName":"Sergey Rykhtorov","country":"Russia","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16555/ax1le","source":"Sopenfi/skindle · Spring 2026"},
  "b1t": {"realName":"Valeriy Vakhovskiy","country":"Ukraine","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18987/b1t","source":"Sopenfi/skindle · Spring 2026"},
  "b4rtin": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17585/b4rtin","source":"PHSix/guess_cspro · Jan 2026"},
  "banjo": {"realName":"Matias Kivistö","country":"Finland","age":22,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "bart4k": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19957/bart4k","source":"PHSix/guess_cspro · Jan 2026"},
  "belchonokk": {"realName":"Andrey Yasinskiy","country":"Russia","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19235/belchonokk","source":"Sopenfi/skindle · Spring 2026"},
  "biguzera": {"realName":"Rodrigo Bittencourt","country":"Brazil","age":29,"role":"IGL","profileUrl":"https://www.hltv.org/player/18141/biguzera","source":"Sopenfi/skindle · Spring 2026"},
  "blamef": {"realName":"Benjamin Bremer","country":"Denmark","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15165/blamef","source":"Sopenfi/skindle · Spring 2026"},
  "blitz": {"realName":"Garidmagnai Byambasuren","country":"Mongolia","age":25,"role":"IGL","profileUrl":"https://www.hltv.org/player/20194/blitz","source":"Sopenfi/skindle · Spring 2026"},
  "bntet": {"realName":null,"country":"Indonesia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7131/bntet","source":"PHSix/guess_cspro · Jan 2026"},
  "bodyy": {"realName":"Alexandre Pianaro","country":"France","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8374/bodyy","source":"Sopenfi/skindle · Spring 2026"},
  "bondik": {"realName":null,"country":"Ukraine","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/2131/bondik","source":"PHSix/guess_cspro · Jan 2026"},
  "boombl4": {"realName":"Kirill Mikhailov","country":"Russia","age":27,"role":"IGL","profileUrl":"https://www.hltv.org/player/11840/boombl4","source":"Sopenfi/skindle · Spring 2026"},
  "brehze": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9136/brehze","source":"PHSix/guess_cspro · Jan 2026"},
  "brnz4n": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20987/brnz4n","source":"PHSix/guess_cspro · Jan 2026"},
  "brollan": {"realName":"Ludvig Brolin","country":"Sweden","age":24,"role":"IGL","profileUrl":"https://www.hltv.org/player/13666/brollan","source":"Sopenfi/skindle · Spring 2026"},
  "buda": {"realName":null,"country":"Argentina","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20607/buda","source":"PHSix/guess_cspro · Jan 2026"},
  "buster": {"realName":null,"country":"Kazakhstan","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11942/buster","source":"PHSix/guess_cspro · Jan 2026"},
  "buzz": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20941/buzz","source":"PHSix/guess_cspro · Jan 2026"},
  "bymas": {"realName":null,"country":"Lithuania","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19015/bymas","source":"PHSix/guess_cspro · Jan 2026"},
  "cacanito": {"realName":null,"country":"North Macedonia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18790/cacanito","source":"PHSix/guess_cspro · Jan 2026"},
  "cadian": {"realName":"Casper Møller","country":"Denmark","age":31,"role":"IGL","profileUrl":"https://www.hltv.org/player/7964/cadian","source":"Sopenfi/skindle · Spring 2026"},
  "cerq": {"realName":null,"country":"Bulgaria","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/11219/cerq","source":"PHSix/guess_cspro · Jan 2026"},
  "chayjesus": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20026/chayjesus","source":"PHSix/guess_cspro · Jan 2026"},
  "chelo": {"realName":"Marcelo Cespedes","country":"Brazil","age":28,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10566/chelo","source":"Sopenfi/skindle · Spring 2026"},
  "childking": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19681/childking","source":"PHSix/guess_cspro · Jan 2026"},
  "chr1zn": {"realName":"Christoffer Storgaard","country":"Denmark","age":20,"role":"IGL","profileUrl":"https://www.hltv.org/player/21983/chr1zn","source":"Sopenfi/skindle · Spring 2026"},
  "controlez": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21398/controlez","source":"PHSix/guess_cspro · Jan 2026"},
  "cool4st": {"realName":null,"country":"Mongolia","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/19537/cool4st","source":"PHSix/guess_cspro · Jan 2026"},
  "cptkurtka023": {"realName":"Arseniy Derevinskiy","country":"Ukraine","age":27,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "cruc1al": {"realName":null,"country":"Netherlands","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/7996/cruc1al","source":"PHSix/guess_cspro · Jan 2026"},
  "cxzi": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17353/cxzi","source":"PHSix/guess_cspro · Jan 2026"},
  "cypher": {"realName":null,"country":"United Kingdom","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18571/cypher","source":"PHSix/guess_cspro · Jan 2026"},
  "dav1deus": {"realName":"David Tapia Maldonado","country":"Chile","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18865/dav1deus","source":"Sopenfi/skindle · Spring 2026"},
  "dav1g": {"realName":null,"country":"Spain","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19509/dav1g","source":"PHSix/guess_cspro · Jan 2026"},
  "decenty": {"realName":"Lucas Bacelar","country":"Brazil","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20183/decenty","source":"Sopenfi/skindle · Spring 2026"},
  "demqq": {"realName":"Sergiy Demchenko","country":"Ukraine","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19733/demqq","source":"Sopenfi/skindle · Spring 2026"},
  "destiny": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9483/destiny","source":"PHSix/guess_cspro · Jan 2026"},
  "device": {"realName":"Nicolai Reedtz","country":"Denmark","age":31,"role":"AWP","profileUrl":"https://www.hltv.org/player/7592/device","source":"Sopenfi/skindle · Spring 2026"},
  "dexter": {"realName":"Christopher Nong","country":"Australia","age":32,"role":"IGL","profileUrl":"https://www.hltv.org/player/9115/dexter","source":"Sopenfi/skindle · Spring 2026"},
  "dgt": {"realName":null,"country":"Uruguay","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14736/dgt","source":"PHSix/guess_cspro · Jan 2026"},
  "djoko": {"realName":"Thomas Pavoni","country":"France","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19738/djoko","source":"Sopenfi/skindle · Spring 2026"},
  "donk": {"realName":"Danil Kryshkovets","country":"Russia","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21167/donk","source":"Sopenfi/skindle · Spring 2026"},
  "draken": {"realName":"William Sundin","country":"Sweden","age":30,"role":"AWP","profileUrl":"https://www.hltv.org/player/9255/draken","source":"Sopenfi/skindle · Spring 2026"},
  "drop": {"realName":"André Wagner de Abreu","country":"Brazil","age":22,"role":"IGL","profileUrl":"https://www.hltv.org/player/19750/drop","source":"Sopenfi/skindle · Spring 2026"},
  "dumau": {"realName":"Eduardo Wolkmer","country":"Brazil","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15698/dumau","source":"Sopenfi/skindle · Spring 2026"},
  "efire": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22414/efire","source":"PHSix/guess_cspro · Jan 2026"},
  "el1an": {"realName":null,"country":"Russia","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/13281/el1an","source":"PHSix/guess_cspro · Jan 2026"},
  "electronic": {"realName":"Denis Sharipov","country":"Russia","age":28,"role":"IGL","profileUrl":"https://www.hltv.org/player/8918/electronic","source":"Sopenfi/skindle · Spring 2026"},
  "elige": {"realName":"Jonathan Jablonowski","country":"USA","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8738/elige","source":"Sopenfi/skindle · Spring 2026"},
  "emiliaqaq": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22922/emiliaqaq","source":"PHSix/guess_cspro · Jan 2026"},
  "erkast": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11141/erkast","source":"PHSix/guess_cspro · Jan 2026"},
  "esenthial": {"realName":"Dmytro Tsvir","country":"Ukraine","age":20,"role":"Rifler","profileUrl":"https://www.hltv.org/player/23643/esenthial","source":"Sopenfi/skindle · Spring 2026"},
  "ex3rcice": {"realName":"Pierre Bulinge","country":"France","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19739/ex3rcice","source":"Sopenfi/skindle · Spring 2026"},
  "exit": {"realName":"Raphael Lacerda","country":"Brazil","age":30,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11154/exit","source":"Sopenfi/skindle · Spring 2026"},
  "f1ku": {"realName":"Maciej Miklas","country":"Poland","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19044/f1ku","source":"Sopenfi/skindle · Spring 2026"},
  "facecrack": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8726/facecrack","source":"PHSix/guess_cspro · Jan 2026"},
  "fallen": {"realName":"Gabriel Toledo","country":"Brazil","age":35,"role":"IGL","profileUrl":"https://www.hltv.org/player/2023/fallen","source":"Sopenfi/skindle · Spring 2026"},
  "fame": {"realName":"Petr Bolyshev","country":"Russia","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20101/fame","source":"Sopenfi/skindle · Spring 2026"},
  "fang": {"realName":null,"country":"Canada","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17372/fang","source":"PHSix/guess_cspro · Jan 2026"},
  "faven": {"realName":null,"country":"Germany","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14932/faven","source":"PHSix/guess_cspro · Jan 2026"},
  "fear": {"realName":"Rodion Smyk","country":"Ukraine","age":25,"role":"IGL","profileUrl":"https://www.hltv.org/player/17803/fear","source":"Sopenfi/skindle · Spring 2026"},
  "felps": {"realName":"João Vasconcellos","country":"Brazil","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9219/felps","source":"Sopenfi/skindle · Spring 2026"},
  "fer": {"realName":"Fernando Alvarenga","country":"Brazil","age":34,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8564/fer","source":"Sopenfi/skindle · Spring 2026"},
  "fitch": {"realName":null,"country":"Kazakhstan","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10052/fitch","source":"PHSix/guess_cspro · Jan 2026"},
  "fl1t": {"realName":"Evgenii Lebedev","country":"Russia","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12732/fl1t","source":"Sopenfi/skindle · Spring 2026"},
  "fl4mus": {"realName":"Timur Marev","country":"Russia","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20994/fl4mus","source":"Sopenfi/skindle · Spring 2026"},
  "flamez": {"realName":"Shahar Shushan","country":"Israel","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16693/flamez","source":"Sopenfi/skindle · Spring 2026"},
  "forester": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13982/forester","source":"PHSix/guess_cspro · Jan 2026"},
  "frozen": {"realName":"David Čerňanský","country":"Slovakia","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9960/frozen","source":"Sopenfi/skindle · Spring 2026"},
  "goofy": {"realName":"Krzysztof Górski","country":"Poland","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15428/goofy","source":"Sopenfi/skindle · Spring 2026"},
  "gratisfaction": {"realName":null,"country":"New Zealand","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/9686/gratisfaction","source":"PHSix/guess_cspro · Jan 2026"},
  "graviti": {"realName":"Filip Brankovic","country":"France","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21969/graviti","source":"Sopenfi/skindle · Spring 2026"},
  "grim": {"realName":"Michael Wince","country":"USA","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13578/grim","source":"Sopenfi/skindle · Spring 2026"},
  "gxx-": {"realName":null,"country":"Kosovo","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/19725/gxx","source":"PHSix/guess_cspro · Jan 2026"},
  "hades": {"realName":"Olek Miskiewicz","country":"Poland","age":26,"role":"AWP","profileUrl":"https://www.hltv.org/player/16848/hades","source":"Sopenfi/skindle · Spring 2026"},
  "hallzerk": {"realName":"Håkon Fjærli","country":"Norway","age":26,"role":"AWP","profileUrl":"https://www.hltv.org/player/12840/hallzerk","source":"Sopenfi/skindle · Spring 2026"},
  "hampus": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9766/hampus","source":"PHSix/guess_cspro · Jan 2026"},
  "hardzao": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16817/hardzao","source":"PHSix/guess_cspro · Jan 2026"},
  "hasteka": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12956/hasteka","source":"PHSix/guess_cspro · Jan 2026"},
  "headtr1ck": {"realName":"Daniil Valitov","country":"Ukraine","age":22,"role":"AWP","profileUrl":"https://www.hltv.org/player/19592/headtr1ck","source":"Sopenfi/skindle · Spring 2026"},
  "heavygod": {"realName":"Nikita Martynenko","country":"Israel","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20447/heavygod","source":"Sopenfi/skindle · Spring 2026"},
  "hen1": {"realName":null,"country":"Brazil","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/8565/hen1","source":"PHSix/guess_cspro · Jan 2026"},
  "henu": {"realName":"Henri Ylilehto","country":"Finland","age":24,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "hext": {"realName":null,"country":"Canada","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18838/hext","source":"PHSix/guess_cspro · Jan 2026"},
  "history": {"realName":null,"country":"Brazil","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/20939/history","source":"PHSix/guess_cspro · Jan 2026"},
  "hobbit": {"realName":"Abay Khassenov","country":"Kazakhstan","age":32,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8528/hobbit","source":"Sopenfi/skindle · Spring 2026"},
  "hooxi": {"realName":"Rasmus Nielsen","country":"Denmark","age":31,"role":"IGL","profileUrl":"https://www.hltv.org/player/10096/hooxi","source":"Sopenfi/skindle · Spring 2026"},
  "hunter-": {"realName":"Nemanja Kovač","country":"Bosnia and Herzegovina","age":30,"role":"Rifler","profileUrl":"https://www.hltv.org/player/3972/hunter","source":"Sopenfi/skindle · Spring 2026"},
  "hypex": {"realName":"Milan Polowiec","country":"Poland","age":22,"role":"AWP","profileUrl":"https://www.hltv.org/player/23766/hypex","source":"Sopenfi/skindle · Spring 2026"},
  "im": {"realName":"Mihai Ivan","country":"Romania","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14759/im","source":"Sopenfi/skindle · Spring 2026"},
  "innocent": {"realName":null,"country":"Poland","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/3669/innocent","source":"PHSix/guess_cspro · Jan 2026"},
  "ins": {"realName":"Joshua Potter","country":"Australia","age":28,"role":"IGL","profileUrl":"https://www.hltv.org/player/11140/ins","source":"Sopenfi/skindle · Spring 2026"},
  "insani": {"realName":"Felipe Yuji","country":"Brazil","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21037/insani","source":"Sopenfi/skindle · Spring 2026"},
  "jabbi": {"realName":"Jakob Nygaard","country":"Denmark","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17956/jabbi","source":"Sopenfi/skindle · Spring 2026"},
  "jackasmo": {"realName":"Nikita Skyba","country":"Ukraine","age":18,"role":"Rifler","profileUrl":"https://www.hltv.org/player/23414/jackasmo","source":"Sopenfi/skindle · Spring 2026"},
  "jackz": {"realName":"Audric Jug","country":"France","age":34,"role":"Rifler","profileUrl":"https://www.hltv.org/player/284/jackz","source":"Sopenfi/skindle · Spring 2026"},
  "jambo": {"realName":"Dmytro Semera","country":"Ukraine","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/23046/jambo","source":"Sopenfi/skindle · Spring 2026"},
  "jame": {"realName":"Dzhami Ali","country":"Russia","age":28,"role":"IGL","profileUrl":"https://www.hltv.org/player/13776/jame","source":"Sopenfi/skindle · Spring 2026"},
  "jamyoung": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19645/jamyoung","source":"PHSix/guess_cspro · Jan 2026"},
  "jba": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21665/jba","source":"PHSix/guess_cspro · Jan 2026"},
  "jcobbb": {"realName":"Jakub Pietruszewski","country":"Poland","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22383/jcobbb","source":"Sopenfi/skindle · Spring 2026"},
  "jdc": {"realName":"Jon de Castro","country":"Germany","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14929/jdc","source":"Sopenfi/skindle · Spring 2026"},
  "jee": {"realName":null,"country":"China","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/20702/jee","source":"PHSix/guess_cspro · Jan 2026"},
  "jeorge": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20333/jeorge","source":"PHSix/guess_cspro · Jan 2026"},
  "jimpphat": {"realName":"Jimi Salo","country":"Finland","age":20,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18850/jimpphat","source":"Sopenfi/skindle · Spring 2026"},
  "jks": {"realName":"Justin Savage","country":"Australia","age":30,"role":"Rifler","profileUrl":"https://www.hltv.org/player/4679/jks","source":"Sopenfi/skindle · Spring 2026"},
  "jl": {"realName":"Justinas Lekavicius","country":"Lithuania","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19206/jl","source":"Sopenfi/skindle · Spring 2026"},
  "jota": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17861/jota","source":"PHSix/guess_cspro · Jan 2026"},
  "jottaaa": {"realName":"Samet Köklü","country":"Turkey","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22361/jottaaa","source":"Sopenfi/skindle · Spring 2026"},
  "jt": {"realName":"Johnny Theodosiou","country":"South Africa","age":27,"role":"IGL","profileUrl":"https://www.hltv.org/player/11630/jt","source":"Sopenfi/skindle · Spring 2026"},
  "junior": {"realName":null,"country":"United States","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/14494/junior","source":"PHSix/guess_cspro · Jan 2026"},
  "jw": {"realName":"Jesper Wecksell","country":"Sweden","age":31,"role":"AWP","profileUrl":"https://www.hltv.org/player/3849/jw","source":"Sopenfi/skindle · Spring 2026"},
  "k1to": {"realName":null,"country":"Germany","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12781/k1to","source":"PHSix/guess_cspro · Jan 2026"},
  "karrigan": {"realName":"Finn Andersen","country":"Denmark","age":36,"role":"IGL","profileUrl":"https://www.hltv.org/player/429/karrigan","source":"Sopenfi/skindle · Spring 2026"},
  "kauez": {"realName":"Kaue Kaschuk","country":"Brazil","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20085/kauez","source":"Sopenfi/skindle · Spring 2026"},
  "kei": {"realName":null,"country":"Poland","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17504/kei","source":"PHSix/guess_cspro · Jan 2026"},
  "kensizor": {"realName":"Artem Kapran","country":"Ukraine","age":20,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22842/kensizor","source":"Sopenfi/skindle · Spring 2026"},
  "keoz": {"realName":null,"country":"Belgium","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15117/keoz","source":"PHSix/guess_cspro · Jan 2026"},
  "khan": {"realName":null,"country":"Kazakhstan","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/23317/khan","source":"PHSix/guess_cspro · Jan 2026"},
  "krad": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12027/krad","source":"PHSix/guess_cspro · Jan 2026"},
  "kraghen": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20300/kraghen","source":"PHSix/guess_cspro · Jan 2026"},
  "krimz": {"realName":"Freddy Johansson","country":"Sweden","age":32,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7528/krimz","source":"Sopenfi/skindle · Spring 2026"},
  "kscerato": {"realName":"Kaike Cerato","country":"Brazil","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15631/kscerato","source":"Sopenfi/skindle · Spring 2026"},
  "kvem": {"realName":null,"country":"Ukraine","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21452/kvem","source":"PHSix/guess_cspro · Jan 2026"},
  "kye": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20385/kye","source":"PHSix/guess_cspro · Jan 2026"},
  "kylar": {"realName":"Kacper Walukiewicz","country":"Poland","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19114/kylar","source":"Sopenfi/skindle · Spring 2026"},
  "kyojin": {"realName":null,"country":"France","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19672/kyojin","source":"PHSix/guess_cspro · Jan 2026"},
  "kyousuke": {"realName":"Maxim Lukin","country":"Russia","age":18,"role":"Rifler","profileUrl":"https://www.hltv.org/player/24177/kyousuke","source":"Sopenfi/skindle · Spring 2026"},
  "kyuubii": {"realName":"Can Ali","country":"Germany","age":21,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "kyxsan": {"realName":"Damjan Stoilkovski","country":"North Macedonia","age":26,"role":"IGL","profileUrl":"https://www.hltv.org/player/19677/kyxsan","source":"Sopenfi/skindle · Spring 2026"},
  "l00m1": {"realName":null,"country":"Sweden","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/21164/l00m1","source":"PHSix/guess_cspro · Jan 2026"},
  "l1hang": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21825/l1hang","source":"PHSix/guess_cspro · Jan 2026"},
  "lack1": {"realName":null,"country":"Kazakhstan","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13240/lack1","source":"PHSix/guess_cspro · Jan 2026"},
  "lake": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22921/lake","source":"PHSix/guess_cspro · Jan 2026"},
  "latto": {"realName":"Bruno Rebelatto","country":"Brazil","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19045/latto","source":"Sopenfi/skindle · Spring 2026"},
  "lekr0": {"realName":"Jonas Olofsson","country":"Sweden","age":33,"role":"IGL","profileUrl":"https://www.hltv.org/player/9261/lekr0","source":"Sopenfi/skindle · Spring 2026"},
  "liazz": {"realName":"Jay Tregillgas","country":"Australia","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10588/liazz","source":"Sopenfi/skindle · Spring 2026"},
  "lnz": {"realName":"Linus Holtäng","country":"Sweden","age":23,"role":"IGL","profileUrl":"https://www.hltv.org/player/19310/lnz","source":"Sopenfi/skindle · Spring 2026"},
  "lucaozy": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18717/lucaozy","source":"PHSix/guess_cspro · Jan 2026"},
  "lucky": {"realName":"Lucas Chastang","country":"France","age":28,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13843/lucky","source":"Sopenfi/skindle · Spring 2026"},
  "luken": {"realName":null,"country":"Argentina","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15914/luken","source":"PHSix/guess_cspro · Jan 2026"},
  "lux": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20563/lux","source":"PHSix/guess_cspro · Jan 2026"},
  "m0nesy": {"realName":"Ilya Osipov","country":"Russia","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/19230/m0nesy","source":"Sopenfi/skindle · Spring 2026"},
  "maden": {"realName":"Pavle Bošković","country":"Montenegro","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11777/maden","source":"Sopenfi/skindle · Spring 2026"},
  "magisk": {"realName":"Emil Reif","country":"Denmark","age":28,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9032/magisk","source":"Sopenfi/skindle · Spring 2026"},
  "magixx": {"realName":"Boris Vorobiev","country":"Russia","age":23,"role":"IGL","profileUrl":"https://www.hltv.org/player/18317/magixx","source":"Sopenfi/skindle · Spring 2026"},
  "magnojez": {"realName":"Kirill Rodnov","country":"Russia","age":21,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "maka": {"realName":"Bryan Canda","country":"France","age":29,"role":"IGL","profileUrl":"https://www.hltv.org/player/13138/maka","source":"Sopenfi/skindle · Spring 2026"},
  "makazze": {"realName":"Drin Shaqiri","country":"Kosovo","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22673/makazze","source":"Sopenfi/skindle · Spring 2026"},
  "malbsmd": {"realName":"Mario Samayoa","country":"Guatemala","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11617/malbsmd","source":"Sopenfi/skindle · Spring 2026"},
  "matys": {"realName":"Matúš Šimko","country":"Slovakia","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21062/matys","source":"Sopenfi/skindle · Spring 2026"},
  "max": {"realName":null,"country":"Uruguay","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12092/max","source":"PHSix/guess_cspro · Jan 2026"},
  "mercury": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20895/mercury","source":"PHSix/guess_cspro · Jan 2026"},
  "michu": {"realName":null,"country":"Poland","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7356/michu","source":"PHSix/guess_cspro · Jan 2026"},
  "mir": {"realName":"Nikolay Bityukov","country":"Russia","age":30,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8789/mir","source":"Sopenfi/skindle · Spring 2026"},
  "misutaaa": {"realName":null,"country":"France","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14176/misutaaa","source":"PHSix/guess_cspro · Jan 2026"},
  "mlhzin": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21286/mlhzin","source":"PHSix/guess_cspro · Jan 2026"},
  "molodoy": {"realName":"Danil Golubenko","country":"Kazakhstan","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/24144/molodoy","source":"Sopenfi/skindle · Spring 2026"},
  "mopoz": {"realName":null,"country":"Spain","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9254/mopoz","source":"PHSix/guess_cspro · Jan 2026"},
  "moseyuh": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21621/moseyuh","source":"PHSix/guess_cspro · Jan 2026"},
  "mutiris": {"realName":"Christopher Fernandes","country":"Portugal","age":33,"role":"IGL","profileUrl":"https://www.hltv.org/player/630/mutiris","source":"Sopenfi/skindle · Spring 2026"},
  "myltsi": {"realName":"Ville Vilkman","country":"Finland","age":21,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "mzinho": {"realName":"Ayush Batbold","country":"Mongolia","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21001/mzinho","source":"Sopenfi/skindle · Spring 2026"},
  "n0rb3r7": {"realName":"David Danielyan","country":"Russia","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16612/n0rb3r7","source":"Sopenfi/skindle · Spring 2026"},
  "n1ssim": {"realName":"Vinicius Pereira","country":"Brazil","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19686/n1ssim","source":"Sopenfi/skindle · Spring 2026"},
  "naf": {"realName":"Keith Markovic","country":"Canada","age":28,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8520/naf","source":"Sopenfi/skindle · Spring 2026"},
  "nafany": {"realName":"Vladislav Gorshkov","country":"Russia","age":25,"role":"IGL","profileUrl":"https://www.hltv.org/player/16921/nafany","source":"Sopenfi/skindle · Spring 2026"},
  "nawwk": {"realName":"Tim Jonasson","country":"Sweden","age":28,"role":"AWP","profileUrl":"https://www.hltv.org/player/13670/nawwk","source":"Sopenfi/skindle · Spring 2026"},
  "nealan": {"realName":null,"country":"Kazakhstan","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11940/nealan","source":"PHSix/guess_cspro · Jan 2026"},
  "neityu": {"realName":"Ryan Aubry","country":"France","age":21,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "nekiz": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9482/nekiz","source":"PHSix/guess_cspro · Jan 2026"},
  "neo": {"realName":"Filip Kubski","country":"Poland","age":39,"role":"Rifler","profileUrl":"https://www.hltv.org/player/165/neo","source":"Sopenfi/skindle · Spring 2026"},
  "neofrag": {"realName":null,"country":"Czech Republic","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/15821/neofrag","source":"PHSix/guess_cspro · Jan 2026"},
  "nertz": {"realName":"Guy Iluz","country":"Israel","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9436/nertz","source":"Sopenfi/skindle · Spring 2026"},
  "nettik": {"realName":null,"country":"New Zealand","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18214/nettik","source":"PHSix/guess_cspro · Jan 2026"},
  "nexa": {"realName":"Nemanja Isaković","country":"Serbia","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9618/nexa","source":"Sopenfi/skindle · Spring 2026"},
  "nickelback": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11498/nickelback","source":"PHSix/guess_cspro · Jan 2026"},
  "nicoodoz": {"realName":"Nico Tamjidi","country":"Denmark","age":26,"role":"AWP","profileUrl":"https://www.hltv.org/player/13602/nicoodoz","source":"Sopenfi/skindle · Spring 2026"},
  "nicx": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21620/nicx","source":"PHSix/guess_cspro · Jan 2026"},
  "niko": {"realName":"Nikola Kovač","country":"Bosnia and Herzegovina","age":29,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10264/niko","source":"Sopenfi/skindle · Spring 2026"},
  "nilo": {"realName":"Linus Bergman","country":"Sweden","age":21,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "nin9": {"realName":null,"country":"Mongolia","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/15072/nin9","source":"PHSix/guess_cspro · Jan 2026"},
  "nitr0": {"realName":"Nick Cannella","country":"USA","age":31,"role":"IGL","profileUrl":"https://www.hltv.org/player/7687/nitr0","source":"Sopenfi/skindle · Spring 2026"},
  "norwi": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19882/norwi","source":"PHSix/guess_cspro · Jan 2026"},
  "noway": {"realName":"Kaiky Santos","country":"Brazil","age":21,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22564/noway","source":"Sopenfi/skindle · Spring 2026"},
  "npl": {"realName":"Andrii Kukharskyi","country":"Ukraine","age":21,"role":"IGL","profileUrl":"https://www.hltv.org/player/21708/npl","source":"Sopenfi/skindle · Spring 2026"},
  "nqz": {"realName":"Lucas Soares","country":"Brazil","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/19694/nqz","source":"Sopenfi/skindle · Spring 2026"},
  "nukkye": {"realName":null,"country":"Lithuania","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13679/nukkye","source":"PHSix/guess_cspro · Jan 2026"},
  "p3kko": {"realName":"Pekko Korkalainen","country":"Finland","age":25,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "pancc": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16314/pancc","source":"PHSix/guess_cspro · Jan 2026"},
  "patsi": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19673/patsi","source":"PHSix/guess_cspro · Jan 2026"},
  "patti": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13077/patti","source":"PHSix/guess_cspro · Jan 2026"},
  "phzy": {"realName":"Love Smidebrant","country":"Sweden","age":24,"role":"AWP","profileUrl":"https://www.hltv.org/player/16726/phzy","source":"Sopenfi/skindle · Spring 2026"},
  "piriajr": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18714/piriajr","source":"PHSix/guess_cspro · Jan 2026"},
  "pkl": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/6593/pkl","source":"PHSix/guess_cspro · Jan 2026"},
  "plopski": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14218/plopski","source":"PHSix/guess_cspro · Jan 2026"},
  "podi": {"realName":"Paavo Heiskanen","country":"Finland","age":22,"role":"AWP","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "pr": {"realName":"Oldřich Nový","country":"Czech Republic","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22279/pr","source":"Sopenfi/skindle · Spring 2026"},
  "puuha": {"realName":"Luka Eklund","country":"Finland","age":19,"role":"IGL","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "qikert": {"realName":null,"country":"Kazakhstan","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13239/qikert","source":"PHSix/guess_cspro · Jan 2026"},
  "queenix": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13749/queenix","source":"PHSix/guess_cspro · Jan 2026"},
  "r1nkle": {"realName":"Artem Moroz","country":"Ukraine","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/20425/r1nkle","source":"Sopenfi/skindle · Spring 2026"},
  "r3salt": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20709/r3salt","source":"PHSix/guess_cspro · Jan 2026"},
  "raalz": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/2898/raalz","source":"PHSix/guess_cspro · Jan 2026"},
  "rain": {"realName":"Håvard Nygaard","country":"Norway","age":32,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8183/rain","source":"Sopenfi/skindle · Spring 2026"},
  "rallen": {"realName":null,"country":"Poland","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/5388/rallen","source":"PHSix/guess_cspro · Jan 2026"},
  "reck": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17378/reck","source":"PHSix/guess_cspro · Jan 2026"},
  "regali": {"realName":null,"country":"Romania","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/20123/regali","source":"PHSix/guess_cspro · Jan 2026"},
  "rez": {"realName":"Fredrik Sterner","country":"Sweden","age":28,"role":"Rifler","profileUrl":"https://www.hltv.org/player/9278/rez","source":"Sopenfi/skindle · Spring 2026"},
  "rigon": {"realName":"Rigon Gashi","country":"Switzerland","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12708/rigon","source":"Sopenfi/skindle · Spring 2026"},
  "riskyb0b": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22460/riskyb0b","source":"PHSix/guess_cspro · Jan 2026"},
  "robiin": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7700/robiin","source":"PHSix/guess_cspro · Jan 2026"},
  "ropz": {"realName":"Robin Kool","country":"Estonia","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/11816/ropz","source":"Sopenfi/skindle · Spring 2026"},
  "roux": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19229/roux","source":"PHSix/guess_cspro · Jan 2026"},
  "ryu": {"realName":"Gytis Glušauskas","country":"Lithuania","age":41,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "s1mple": {"realName":"Oleksandr Kostyliev","country":"Ukraine","age":28,"role":"AWP","profileUrl":"https://www.hltv.org/player/7998/s1mple","source":"Sopenfi/skindle · Spring 2026"},
  "s1n": {"realName":null,"country":"Germany","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20104/s1n","source":"PHSix/guess_cspro · Jan 2026"},
  "s1ren": {"realName":"Pavel Ogloblin","country":"Russia","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18506/s1ren","source":"Sopenfi/skindle · Spring 2026"},
  "saadzin": {"realName":"Guilherme Pacheco","country":"Brazil","age":22,"role":"AWP","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "saffee": {"realName":"Rafael Costa","country":"Brazil","age":31,"role":"AWP","profileUrl":"https://www.hltv.org/player/18835/saffee","source":"Sopenfi/skindle · Spring 2026"},
  "salazar": {"realName":null,"country":"Denmark","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/21379/salazar","source":"PHSix/guess_cspro · Jan 2026"},
  "scream": {"realName":"Adil Benrlitom","country":"Belgium","age":32,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7390/scream","source":"Sopenfi/skindle · Spring 2026"},
  "sdy": {"realName":"Viktor Orudzhev","country":"Ukraine","age":29,"role":"IGL","profileUrl":"https://www.hltv.org/player/12731/sdy","source":"Sopenfi/skindle · Spring 2026"},
  "senzu": {"realName":"Munkhbold Azbayar","country":"Mongolia","age":20,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20903/senzu","source":"Sopenfi/skindle · Spring 2026"},
  "sh1ro": {"realName":"Dmitry Sokolov","country":"Russia","age":25,"role":"AWP","profileUrl":"https://www.hltv.org/player/16920/sh1ro","source":"Sopenfi/skindle · Spring 2026"},
  "shalfey": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17011/shalfey","source":"PHSix/guess_cspro · Jan 2026"},
  "sinnopsyy": {"realName":null,"country":"Kosovo","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18120/sinnopsyy","source":"PHSix/guess_cspro · Jan 2026"},
  "sirah": {"realName":"William Kjærsgaard","country":"Denmark","age":19,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "siuhy": {"realName":"Kamil Szkaradek","country":"Poland","age":24,"role":"IGL","profileUrl":"https://www.hltv.org/player/16820/siuhy","source":"Sopenfi/skindle · Spring 2026"},
  "sjuush": {"realName":"Rasmus Beck","country":"Denmark","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14148/sjuush","source":"Sopenfi/skindle · Spring 2026"},
  "sk0r": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18638/sk0r","source":"PHSix/guess_cspro · Jan 2026"},
  "sl3nd": {"realName":"Henrich Hevesi","country":"Hungary","age":22,"role":"AWP","profileUrl":"https://www.hltv.org/player/20870/sl3nd","source":"Sopenfi/skindle · Spring 2026"},
  "slaxz-": {"realName":null,"country":"Germany","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/15370/slaxz","source":"PHSix/guess_cspro · Jan 2026"},
  "smooya": {"realName":null,"country":"United Kingdom","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/11271/smooya","source":"PHSix/guess_cspro · Jan 2026"},
  "snappi": {"realName":"Marco Pfeiffer","country":"Denmark","age":36,"role":"IGL","profileUrl":"https://www.hltv.org/player/922/snappi","source":"Sopenfi/skindle · Spring 2026"},
  "snax": {"realName":"Janusz Pogorzelski","country":"Poland","age":33,"role":"IGL","profileUrl":"https://www.hltv.org/player/2553/snax","source":"Sopenfi/skindle · Spring 2026"},
  "snow": {"realName":"João Vinicius","country":"Brazil","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20171/snow","source":"Sopenfi/skindle · Spring 2026"},
  "sonic": {"realName":"Aran Groesbeek","country":"South Africa","age":27,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8711/sonic","source":"Sopenfi/skindle · Spring 2026"},
  "spinx": {"realName":"Lotan Giladi","country":"Israel","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/18221/spinx","source":"Sopenfi/skindle · Spring 2026"},
  "spooke": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19064/spooke","source":"PHSix/guess_cspro · Jan 2026"},
  "stadodo": {"realName":null,"country":"Portugal","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/11205/stadodo","source":"PHSix/guess_cspro · Jan 2026"},
  "staehr": {"realName":"Victor Staehr","country":"Denmark","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20304/staehr","source":"Sopenfi/skindle · Spring 2026"},
  "stanislaw": {"realName":"Peter Jarguz","country":"Canada","age":32,"role":"IGL","profileUrl":"https://www.hltv.org/player/8507/stanislaw","source":"Sopenfi/skindle · Spring 2026"},
  "starry": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20254/starry","source":"PHSix/guess_cspro · Jan 2026"},
  "stavn": {"realName":"Martin Lund","country":"Denmark","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10994/stavn","source":"Sopenfi/skindle · Spring 2026"},
  "stewie2k": {"realName":"Jake Yip","country":"USA","age":28,"role":"IGL","profileUrl":"https://www.hltv.org/player/8797/stewie2k","source":"Sopenfi/skindle · Spring 2026"},
  "summer": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7028/summer","source":"PHSix/guess_cspro · Jan 2026"},
  "susp": {"realName":"Tim Ångström","country":"Sweden","age":21,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21163/susp","source":"Sopenfi/skindle · Spring 2026"},
  "swisher": {"realName":null,"country":"United States","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16599/swisher","source":"PHSix/guess_cspro · Jan 2026"},
  "tabsen": {"realName":"Johannes Wodarz","country":"Germany","age":31,"role":"IGL","profileUrl":"https://www.hltv.org/player/5794/tabsen","source":"Sopenfi/skindle · Spring 2026"},
  "tauson": {"realName":"Sebastian Tauson Lindelof","country":"Denmark","age":21,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20301/tauson","source":"Sopenfi/skindle · Spring 2026"},
  "techno": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20275/techno","source":"PHSix/guess_cspro · Jan 2026"},
  "teses": {"realName":"René Madsen","country":"Denmark","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12018/teses","source":"Sopenfi/skindle · Spring 2026"},
  "tiger": {"realName":null,"country":"China","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/20808/tiger","source":"PHSix/guess_cspro · Jan 2026"},
  "tn1r": {"realName":"Andrey Tatarinovich","country":"Belarus","age":25,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19808/tn1r","source":"Sopenfi/skindle · Spring 2026"},
  "torzsi": {"realName":"Ádám Torzsás","country":"Hungary","age":24,"role":"AWP","profileUrl":"https://www.hltv.org/player/18072/torzsi","source":"Sopenfi/skindle · Spring 2026"},
  "travis": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16948/travis","source":"PHSix/guess_cspro · Jan 2026"},
  "try": {"realName":null,"country":"Argentina","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/19869/try","source":"PHSix/guess_cspro · Jan 2026"},
  "tuurtle": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/14394/tuurtle","source":"PHSix/guess_cspro · Jan 2026"},
  "twist": {"realName":null,"country":"Sweden","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7443/twist","source":"PHSix/guess_cspro · Jan 2026"},
  "twistzz": {"realName":"Russel Van Dulken","country":"Canada","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/10394/twistzz","source":"Sopenfi/skindle · Spring 2026"},
  "uli": {"realName":"Samu Leirilaakso","country":"Finland","age":28,"role":"Rifler","profileUrl":null,"source":"Sopenfi/skindle · Spring 2026"},
  "ultimate": {"realName":"Roland Tomkowiak","country":"Poland","age":22,"role":"AWP","profileUrl":"https://www.hltv.org/player/21763/ultimate","source":"Sopenfi/skindle · Spring 2026"},
  "venomzera": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21288/venomzera","source":"PHSix/guess_cspro · Jan 2026"},
  "vexite": {"realName":"Declan Portelli","country":"Australia","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/17384/vexite","source":"Sopenfi/skindle · Spring 2026"},
  "vini": {"realName":"Vinicius Figueiredo","country":"Brazil","age":27,"role":"IGL","profileUrl":"https://www.hltv.org/player/12822/vini","source":"Sopenfi/skindle · Spring 2026"},
  "volt": {"realName":"Sebastian Maloș","country":"Romania","age":24,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20358/volt","source":"Sopenfi/skindle · Spring 2026"},
  "vsm": {"realName":null,"country":"Brazil","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16816/vsm","source":"PHSix/guess_cspro · Jan 2026"},
  "w0nderful": {"realName":"Ihor Zhdanov","country":"Ukraine","age":21,"role":"AWP","profileUrl":"https://www.hltv.org/player/20127/w0nderful","source":"Sopenfi/skindle · Spring 2026"},
  "westmelon": {"realName":null,"country":"China","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/16551/westmelon","source":"PHSix/guess_cspro · Jan 2026"},
  "wicadia": {"realName":"Ali Haydar Yalçın","country":"Turkey","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/21243/wicadia","source":"Sopenfi/skindle · Spring 2026"},
  "wood7": {"realName":null,"country":"Brazil","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/14390/wood7","source":"PHSix/guess_cspro · Jan 2026"},
  "woro2k": {"realName":"Volodymyr Veletniuk","country":"Ukraine","age":25,"role":"AWP","profileUrl":"https://www.hltv.org/player/16885/woro2k","source":"Sopenfi/skindle · Spring 2026"},
  "woxic": {"realName":"Özgür Eker","country":"Turkey","age":28,"role":"AWP","profileUrl":"https://www.hltv.org/player/8574/woxic","source":"Sopenfi/skindle · Spring 2026"},
  "xant3r": {"realName":null,"country":"Russia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20387/xant3r","source":"PHSix/guess_cspro · Jan 2026"},
  "xantares": {"realName":"Ismailcan Dörtkardeş","country":"Turkey","age":31,"role":"Rifler","profileUrl":"https://www.hltv.org/player/7938/xantares","source":"Sopenfi/skindle · Spring 2026"},
  "xerolte": {"realName":null,"country":"Mongolia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20703/xerolte","source":"PHSix/guess_cspro · Jan 2026"},
  "xertion": {"realName":"Dorian Berman","country":"Israel","age":22,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20312/xertion","source":"Sopenfi/skindle · Spring 2026"},
  "xfl0ud": {"realName":"Yasin Koç","country":"Turkey","age":23,"role":"Rifler","profileUrl":"https://www.hltv.org/player/19187/xfl0ud","source":"Sopenfi/skindle · Spring 2026"},
  "xielo": {"realName":"Vladislav Lysov","country":"Russia","age":20,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22471/xielo","source":"Sopenfi/skindle · Spring 2026"},
  "xkacpersky": {"realName":"Kacper Gabara","country":"Poland","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/23372/xkacpersky","source":"Sopenfi/skindle · Spring 2026"},
  "xsepower": {"realName":null,"country":"Russia","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/12733/xsepower","source":"PHSix/guess_cspro · Jan 2026"},
  "yekindar": {"realName":"Mareks Gaļinskis","country":"Latvia","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/13915/yekindar","source":"Sopenfi/skindle · Spring 2026"},
  "yuurih": {"realName":"Yuri Santos","country":"Brazil","age":26,"role":"Rifler","profileUrl":"https://www.hltv.org/player/12553/yuurih","source":"Sopenfi/skindle · Spring 2026"},
  "yxngstxr": {"realName":"Simon Boije","country":"Sweden","age":21,"role":"Rifler","profileUrl":"https://www.hltv.org/player/22047/yxngstxr","source":"Sopenfi/skindle · Spring 2026"},
  "z4kr": {"realName":null,"country":"China","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/18744/z4kr","source":"PHSix/guess_cspro · Jan 2026"},
  "zero": {"realName":null,"country":"Slovakia","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/8413/zero","source":"PHSix/guess_cspro · Jan 2026"},
  "zerrofix": {"realName":null,"country":"Ukraine","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/23415/zerrofix","source":"PHSix/guess_cspro · Jan 2026"},
  "zevy": {"realName":null,"country":"Brazil","age":null,"role":"AWP","profileUrl":"https://www.hltv.org/player/19692/zevy","source":"PHSix/guess_cspro · Jan 2026"},
  "zont1x": {"realName":"Myroslav Plakhotia","country":"Ukraine","age":21,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20423/zont1x","source":"Sopenfi/skindle · Spring 2026"},
  "zorte": {"realName":"Aleksandr Zagodyrenko","country":"Russia","age":28,"role":"AWP","profileUrl":"https://www.hltv.org/player/15662/zorte","source":"Sopenfi/skindle · Spring 2026"},
  "ztr": {"realName":"Erik Gustafsson","country":"Sweden","age":23,"role":"IGL","profileUrl":"https://www.hltv.org/player/16486/ztr","source":"Sopenfi/skindle · Spring 2026"},
  "zweih": {"realName":"Ivan Gogin","country":"Russia","age":19,"role":"Rifler","profileUrl":"https://www.hltv.org/player/23685/zweih","source":"Sopenfi/skindle · Spring 2026"},
  "zyphon": {"realName":null,"country":"Denmark","age":null,"role":"Rifler","profileUrl":"https://www.hltv.org/player/20090/zyphon","source":"PHSix/guess_cspro · Jan 2026"},
  "zywoo": {"realName":"Mathieu Herbaut","country":"France","age":25,"role":"AWP","profileUrl":"https://www.hltv.org/player/11893/zywoo","source":"Sopenfi/skindle · Spring 2026"},
} as const

export const PLAYER_METADATA_STATS = {
  enrichedPlayers: 317,
  withRealName: 183,
  withCountry: 317,
  withAge: 183,
  withRole: 317,
  withProfileUrl: 300,
} as const

export function metadataForAlias(alias: string) {
  return PLAYER_METADATA[alias.toLocaleLowerCase('en-US')] ?? null
}
